apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.helm.sh/stable'
    chart: chartmuseum
    helm:
      parameters:
        - name: env.open.STORAGE_AMAZON_BUCKET
          value: "gitops-helm-summit-chartmuseum"
        - name: env.open.STORAGE_AMAZON_PREFIX
          value: "/"
        - name: env.open.STORAGE_AMAZON_REGION
          value: "eu-west-1"
        - name: service.type
          value: LoadBalancer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
