apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://chartmuseum.github.io/charts'
    targetRevision: 3.1.0
    helm:
      values: |
        env:
          secret:
            BASIC_AUTH_USER: <user>
            BASIC_AUTH_PASS: <pass>
          open:
            DISABLE_API: false
            STORAGE_AMAZON_BUCKET: gitops-helm-summit-chartmuseum
            STORAGE_AMAZON_PREFIX: "/"
            STORAGE_AMAZON_REGION: eu-west-1
            AUTH_ANONYMOUS_GET: true
            ALLOW_OVERWRITE: true
        service:
          type: LoadBalancer
    chart: chartmuseum
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

