apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.helm.sh/stable'
    chart: chartmuseum
    helm:
      parameters:
        - name: env.open.STORAGE_AMAZON_BUCKET
          value: ""
        - name: env.open.STORAGE_AMAZON_PREFIX
          value: ""
        - name: env.open.STORAGE_AMAZON_REGION
          value: ""
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
