apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.helm.sh/stable'
    chart: chartmuseum
    helm:
      parameters:
        - name: app
          value: $ARGOCD_APP_NAME
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

      

