apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://a6412244e5de940e7ba0eb62fa02eb36-1300587414.eu-west-1.elb.amazonaws.com:8080'
    chart: todo
    targetRevision: 0.1.1
    helm:
      releaseName: todo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

