on:
  push:
    branches:
      - main
jobs:
  create-infra:
    name: Setup Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-central-1'
    steps:
      - uses: actions/checkout@v2
      - run: cd iac
      - run: terraform init
      - run: terraform apply -auto-approve
